package com.example.calculator.util

object Constants {
    const val EMPTY = ""
    const val ZERO = "0"
    const val PLUS = "+"
    const val MINUS = "-"
    const val DIV = "%"
    const val TIMES = "x"
    const val FIRST_OPERAND = "firstOperand"
    const val SECOND_OPERAND = "secondOperand"
    const val OPERATOR = "operator"
    const val ENUM = "enum"
    const val COMA = ","
    const val DOT = "."
    const val PATTERN = "#.##"
    const val DIVISION_BY_ZERO_KEY = "division_by_zero"
    const val INCOMPLETE_OPERATION_KEY = "incomplete_operation"
    const val INVALID_NUMBER_KEY = "invalid_number"
    const val NONE_KEY = "none"
    const val SUCCESS_KEY = "success"
    const val DIVISION_BY_ZERO_MSG = "Division by zero"
    const val INCOMPLETE_OPERATION_MSG = "Incomplete operation"
    const val INVALID_NUMBER_MSG = "Invalid operator/s number/s"
}
